zmq: "tcp://10.42.0.55:5555"
rows:
  - class: row
    cols:
      - class: col-md-4 col-md-offset-4
        widget_type: Card
        title: Velocidad del viento
        metric: wind_speed
        icon: fas fa-tachometer-alt
  - class: row
    cols:
      - class: col-md-12
        widget_type: Graph
        title: Velocidad del viento
        metric: wind_speed
